version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_ADDR: redis:6379
      SERVER_ADDR: :8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
